version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=tictactoe
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - tictactoe-network

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tictactoe
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U user -d tictactoe']
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - tictactoe-network

volumes:
  postgres_data:

networks:
  tictactoe-network:
    driver: bridge
